name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Instantiation
      id: instantiation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Instantiation
        setup-command: ''
        command: python3 -m unittest discover -s tests_autograder -p "tests_all.py"
        # command: python3 -m unittest tests_autograder/test_dynamic_array.TestDynamicArray.test_instantiation
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INSTANTIATION_RESULTS: "${{steps.instantiation.outputs.result}}"
      with:
        runners: instantiation
